using System;
using System.Linq;

using FrooxEngine;

using HarmonyLib;

using ResoniteModLoader;

namespace WorldOrbDynVars
{
	public sealed class WorldOrbDynVars : ResoniteMod
	{
		// UPDATE VERSIONS HERE AND IN GITHUB ACTIONS. DON'T FORGET RELEASE NOTES!
		internal const string VersionConstant = "1.0.2";

		public override string Name => "WorldOrbDynVars";

		public override string Author => "Dominion";

		public override string Version => VersionConstant;

		public override string Link => "https://github.com/Cyberboss/WorldOrbDynVars";

		[AutoRegisterConfigKey]
		private static readonly ModConfigurationKey<bool> Enabled = new ModConfigurationKey<bool>("Enabled", "Mod Enabled", () => true);

		private static ModConfiguration? Config;

		public override void OnEngineInit()
		{
			Config = GetConfiguration()!;
			Config.Save(true);
			Harmony harmony = new("net.dextraspace.WorldOrbDynVars");
			harmony.PatchAll();
		}

		[HarmonyPatch(typeof(WorldOrb), "OnStart")]
		class WorldOrb_OnStart_Patch
		{
			public static void Postfix(WorldOrb __instance)
			{
				SessionJoinParameters asdf = null;
				Slot? slot = null;
				try
				{
					var componentRef = __instance.ReferenceID;
					Debug($"Locally attached {nameof(WorldOrb)} component. Ref: {componentRef}");
					if (Config?.GetValue(Enabled) != true)
					{
						Debug($"Mod is disabled, ignoring...");
						return;
					}

					var parentSlot = __instance.Slot;
					Msg($"Mod is enabled. Running on {nameof(WorldOrb)} component ref \"{componentRef}\" under slot ref: {parentSlot.ReferenceID}");

					var localUser = __instance.World.LocalUser;
					var localUserID = localUser.UserID;
					if (String.IsNullOrWhiteSpace(localUserID))
					{
						Msg("Local user does not appear to be loaded. Assuming because the user is in local home and aborting...");
						return;
					}

					var slotName = $"WorldOrbDynVars.{localUserID}";

					slot = __instance.Slot.Children.FirstOrDefault(child => child.Name == slotName);
					bool slotPreExists = slot != null;
					if (slotPreExists)
						Warn($"Slot {slotName} appears to already exist for local user {localUserID} under {nameof(WorldOrb)} component ref: {componentRef}. That's strange... Attaching another DestroyOnLeave for sanity.");
					else
					{
						Msg($"Building new child slot: {slotName}...");
						slot = __instance.Slot.AddSlot(slotName, false);
					}

					var destroyOnLeave = slot!.AttachComponent<DestroyOnUserLeave>();
					destroyOnLeave.TargetUser.User.Value = localUser.ReferenceID;

					if (slotPreExists)
						return;

					var comment = slot.AttachComponent<Comment>();
					comment.Text.Value = $"Dynamic variable space generated by the WorldOrbDynVars mod v{VersionConstant}.";

					var dvs = slot.AttachComponent<DynamicVariableSpace>();
					dvs.SpaceName.Value = "WorldOrbDynVars";

					var worldUrl = slot.AttachComponent<DynamicValueVariable<Uri>>();
					worldUrl.VariableName.Value = $"WorldOrbDynVars/Url";

					var worldUrlValueCopy = slot.AttachComponent<ValueCopy<Uri>>();
					worldUrlValueCopy.Source.Value = __instance.URL_Field.ReferenceID;
					worldUrlValueCopy.Target.Value = worldUrl.Value.ReferenceID;

					int i = 0;
					var activeSessionsField = __instance.ActiveSessionURLs_Field;
					foreach (var sessionField in activeSessionsField.Elements)
					{
						var sessionRef = sessionField.ReferenceID;

						var sessionUrl = slot.AttachComponent<DynamicValueVariable<Uri>>();
						sessionUrl.VariableName.Value = $"WorldOrbDynVars/SessionUrl.{i}";

						var sessionUrlValueCopy = slot.AttachComponent<ValueCopy<Uri>>();
						sessionUrlValueCopy.Source.Value = sessionField.ReferenceID;
						sessionUrlValueCopy.Target.Value = sessionUrl.Value.ReferenceID;

						++i;
					}

					Debug($"Done with component ref: {componentRef}");
				}
				catch (Exception ex)
				{
					try
					{
						Error($"Something has gone horribly wrong. Please report this on GitHub at Cyberboss/WorldOrbDynVars: {ex}");
						if (slot != null)
						{
							Msg($"Attempting to cleanup the slot we created...");
							try
							{
								slot.Destroy();
							}
							catch (Exception innerEx)
							{
								Error($"Slot cleanup failed too, we're cooked! {innerEx}");
							}
						}
					}
					catch
					{
						// even logging has failed us. Froox help you
					}
				}
			}
		}
	}
};
